### ISSUE TITLE
Can not define custom url_fetcher

### ISSUE THREAD

**Issue by acouette** [SimonSapin/Flask-WeasyPrint#9]
kwargs['url_fetcher'] is always overriden when instanciating HTML().

I would like to define a custom url_fetcher. Is there a specific reason why we can't ?

**Comment by SimonSapin** [comment]
The whole point of Flask-WeasyPrint is to provide a `url_fetcher`. `flask_weasyprint.HTML` is just a convenience wrapper that sets it implicitly.

I recommend using `weasyprint.HTML` directly rather than `flask_weasyprint.HTML`, and separately use `flask_weasyprint.make_url_fetcher()` possibly for use in your own `url_fetcher`.

**Comment by acouette** [comment]
Thanks for your reply. 
I now realize that I am only using render_pdf() of Flask-WeasyPrint (which represents like 5% of the code). I will then follow your advice and get rid of Flask-WeasyPrint as it does not suit my need.
Thanks
